services:
  mock_rpc:
    build:
      context: .
      dockerfile: mock_rpc.Dockerfile
    container_name: strata_dashboards_mock_rpc
    ports:
      - "8545:8545"
      - "8546:8546"
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: alpen_dashboards_backend
    depends_on:
      - mock_rpc
    environment:
      STRATA_RPC_URL: http://mock_rpc:8545
      STRATA_BRIDGE_RPC_URL: http://mock_rpc:8546
      BUNDLER_URL: https://bundler.testnet.alpenlabs.io/health
      USER_OPS_QUERY_URL: https://explorer.testnet.alpenlabs.io/api/v2/proxy/account-abstraction/operations
      ACCOUNTS_QUERY_URL: https://explorer.testnet.alpenlabs.io/api/v2/proxy/account-abstraction/accounts
      ACTIVITY_STATS_REFETCH_INTERVAL_S: 120
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: alpen_dashboards_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
