services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: alpen_dashboards_backend
    depends_on:
      - mock_rpc
    environment:
      ALPEN_RPC_URL: http://localhost:8545
      ALPEN_BRIDGE_RPC_URL: http://locahost:8546
      BUNDLER_URL: https://bundler.testnet.alpenlabs.io/health
      USER_OPS_QUERY_URL: https://explorer.testnet.alpenlabs.io/api/v2/proxy/account-abstraction/operations
      ACCOUNTS_QUERY_URL: https://explorer.testnet.alpenlabs.io/api/v2/proxy/account-abstraction/accounts
      NETWORK_STATUS_REFETCH_INTERVAL_S: 120
      BRIDGE_STATUS_REFETCH_INTERVAL_S: 120
      ACTIVITY_STATS_REFETCH_INTERVAL_S: 120
      ACTIVITY_QUERY_PAGE_SIZE: 5
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: alpen_dashboards_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
